# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the "docs/" directory with Sphinx
sphinx:
   configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  jobs:
    pre_install:
      - python -m pip install pdm
    install:
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install --with docs --with arrays
