name: Draft PDF
on:
  push:
    paths:
      - paper/**
      - .github/workflows/joss.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
        with:
          journal: joss
          # This should be the path to the paper within your repo.
          paper-path: paper/paper.md
      - name: Upload
        id: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: paper
          # This is the output path where Pandoc will write the compiled
          # PDF. Note, this should be the same directory as the input
          # paper.md
          path: paper/paper.pdf
          archive: false

      - name: Find Comment
        uses: peter-evans/find-comment@v4
        id: find-comment
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-author: 'github-actions[bot]'
          body-includes: "JOSS PDF Built"
      - name: Update Comment
        env:
          ARTIFACT_URL: "${{ steps.upload-artifacts.outputs.artifact-url }}"
          HEAD_SHA: "${{ env.HEAD_SHA }}"
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ env.PR_NUMBER }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |-
            JOSS PDF Built! View it below

            | Name     | Link                    |
            | -------- | ----------------------- |
            | Commit   | ${{ env.HEAD_SHA }}     |
            | Download | ${{ env.ARTIFACT_URL }} |