name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


permissions:
  contents: read

jobs:
  ruff:
    name: Ruff Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  black:
    name: Black Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
