name: LinkML Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linkml:
    strategy:
      matrix:
        platform: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.9", "3.12"]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout LinkML
        uses: actions/checkout@v4
        with:
          repository: linkml/linkml
          path: linkml
          ref: main
          fetch-depth: 0

      - name: Checkout numpydantic
        uses: actions/checkout@v4
        with:
          path: numpydantic

      - name: Install uv and setup uv caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dynamic versioning plugin
        run: poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add checked out numpydantic to poetry deps
        working-directory: linkml
        run: uv add --editable '../numpydantic'

      - name: Install dependencies
        working-directory: linkml
        run: uv sync --all-groups

      - name: Force uninstall and reinstall
        working-directory: linkml
        run: |
          uv run pip uninstall -y numpydantic
          uv run pip install -e ../numpydantic

      - name: print numpydantic version and path
        working-directory: linkml
        run: uv run python -c 'import numpydantic; from importlib.metadata import version; print(numpydantic.__file__); print(version("numpydantic"))'

      - name: Run LinkML Numpydantic Tests
        run: uv run pytest -m pydanticgen_npd
        working-directory: linkml
